// backend/src/db/models/AnnualResult.js
"use strict";

const mongoose       = require("mongoose");
const { v4: uuidv4 } = require("uuid");

/**
 * AnnualResult — one per student per academic year per class.
 *
 * Stores the computed annual average and per-term breakdown.
 * Generated by annualGrading.service.js after term results are computed.
 */

const termAverageSchema = new mongoose.Schema(
  {
    term:          { type: Number, required: true },
    average:       { type: Number, default: 0 },
    overallGrade:  { type: String, default: null },
    isComplete:    { type: Boolean, default: false },
  },
  { _id: false }
);

const annualResultSchema = new mongoose.Schema(
  {
    _id: { type: String, default: uuidv4 },

    schoolId:     { type: String, required: true, index: true },
    academicYear: { type: String, required: true, index: true },
    classId:      { type: String, required: true, index: true },
    studentId:    { type: String, required: true, index: true },

    // Denormalised
    studentName: { type: String, default: null },
    admissionNo: { type: String, default: null },
    className:   { type: String, default: null },

    // Per-term averages
    termAverages: { type: [termAverageSchema], default: [] },

    // Annual average
    annualAverage:   { type: Number, default: 0 },
    overallGrade:    { type: String, default: null },
    overallRemark:   { type: String, default: null },

    // Promotion
    promotionStatus: {
      type:    String,
      enum:    ["promoted", "repeated", "conditional", "graduated", "pending"],
      default: "pending",
    },
    promotionThreshold: { type: Number, default: null },

    // Rankings
    classPosition:  { type: Number, default: null },
    schoolPosition: { type: Number, default: null },
    totalInClass:   { type: Number, default: null },
    totalInSchool:  { type: Number, default: null },

    // Pass / fail
    isPassing: { type: Boolean, default: false },

    // Publishing
    isPublished: { type: Boolean, default: false },
    publishedAt: { type: Date,    default: null  },
    isLocked:    { type: Boolean, default: false },
    lockedAt:    { type: Date,    default: null  },

    // Sync
    syncStatus:   { type: String, enum: ["synced", "pending", "conflict"], default: "pending" },
    lastSyncedAt: { type: Date,   default: null },
    deletedAt:    { type: Date,   default: null },
  },
  {
    _id:       false,
    timestamps: true,
    toJSON:    { virtuals: true },
    toObject:  { virtuals: true },
  }
);

annualResultSchema.index(
  { schoolId: 1, academicYear: 1, classId: 1, studentId: 1 },
  { unique: true, sparse: true }
);
annualResultSchema.index({ schoolId: 1, academicYear: 1, classPosition: 1 });
annualResultSchema.index({ schoolId: 1, isPublished: 1 });

module.exports = mongoose.model("AnnualResult", annualResultSchema);
