// backend/src/db/models/Message.js
"use strict";

const mongoose       = require("mongoose");
const { v4: uuidv4 } = require("uuid");

// Signing of attachment URLs happens in toClientJSON below, at read time —
// see utils/mediaSignature.js for why the stored value must stay unsigned.
const mediaSignature = require("../../utils/mediaSignature");

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * MESSAGE
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * One message in one conversation.
 *
 * Key design decisions:
 *
 *   seq
 *     A server-assigned, monotonic number per conversation, and the ONLY
 *     sort key. Device clocks in this deployment are frequently wrong — a
 *     phone that has been offline for a week may be minutes or hours out —
 *     so sorting by any client timestamp would interleave an offline
 *     sender's messages differently for different readers. Two people must
 *     see the same conversation in the same order, which means the server
 *     decides.
 *
 *   deviceCreatedAt
 *     What the sender's clock said when they composed it, kept because
 *     "sent Tuesday while offline, delivered Thursday" is worth showing.
 *     Display only. Never sort by it.
 *
 *   _id supplied by the client
 *     The mobile outbox retries on a flaky link. Letting the device choose
 *     the id makes a replayed send collide on the primary key instead of
 *     posting the message twice.
 *
 *   deletedAt, never a real delete
 *     A school holding records about minors may need a conversation months
 *     after the participants would prefer it gone. Deleting hides the body
 *     from participants; it does not destroy the row, and an admin audit
 *     can still reach it.
 *
 *   attachments
 *     Metadata only. Bytes live in the uploads tree that server.js already
 *     serves, so messages stay small enough to sync over a poor link.
 * ═══════════════════════════════════════════════════════════════════════════
 */

const attachmentSchema = new mongoose.Schema(
  {
    kind: {
      type:    String,
      enum:    ["image", "document", "audio", "video"],
      default: "document",
    },
    url:      { type: String, required: true },
    name:     { type: String, default: null },
    mimeType: { type: String, default: null },
    /** Bytes. Shown before download so nobody spends their data blind. */
    size:     { type: Number, default: null },
    /** Voice notes and video: seconds. */
    duration: { type: Number, default: null },
  },
  { _id: false }
);

const reactionSchema = new mongoose.Schema(
  {
    /** A short emoji or token, e.g. "👍". */
    key:  { type: String, required: true },
    kind: { type: String, enum: ["user", "guardian"], default: "user" },
    by:   { type: String, required: true },
    at:   { type: Date,   default: Date.now },
  },
  { _id: false }
);

const senderSchema = new mongoose.Schema(
  {
    kind: { type: String, enum: ["user", "guardian"], required: true },
    id:   { type: String, required: true },
    /** Denormalised so a thread renders without joining users. */
    name: { type: String, default: null },
    role: { type: String, default: null },
  },
  { _id: false }
);

const messageSchema = new mongoose.Schema(
  {
    /** Client-suppliable, so an offline retry is idempotent. */
    _id: { type: String, default: uuidv4 },

    conversationId: {
      type:     String,
      ref:      "Conversation",
      required: true,
      index:    true,
    },

    schoolId: { type: String, required: true, index: true },

    /** Server-assigned, monotonic within the conversation. The sort key. */
    seq: { type: Number, required: true },

    sender: { type: senderSchema, required: true },

    body: { type: String, default: "", trim: true },

    attachments: { type: [attachmentSchema], default: [] },

    /** Threading: the message this one replies to, within the same thread. */
    replyTo: { type: String, ref: "Message", default: null },

    /**
     * Set when the message was generated by the system rather than typed —
     * "Results published", "Marked absent". Lets clients style it apart from
     * a person speaking, and keeps automated notices out of reply chains.
     */
    systemEvent: { type: String, default: null },

    reactions: { type: [reactionSchema], default: [] },

    /** What the sender's clock said. Display only — see the header. */
    deviceCreatedAt: { type: Date, default: null },

    editedAt: { type: Date, default: null },

    // ── Soft delete ──────────────────────────────────────────────────────
    deletedAt:   { type: Date,   default: null },
    deletedBy:   { type: String, default: null },
    deleteReason:{ type: String, default: null },
  },
  {
    _id:        false,
    timestamps: true,
    toJSON:     { virtuals: true },
    toObject:   { virtuals: true },
  }
);

// ── Indexes ─────────────────────────────────────────────────────────────────

// The thread read: "messages in this conversation, in order". Also the
// pagination cursor (seq < X), so it must be a compound index.
messageSchema.index({ conversationId: 1, seq: -1 });

// No two messages may share a seq within a thread. This is what makes the
// ordering guarantee real rather than merely intended.
messageSchema.index({ conversationId: 1, seq: 1 }, { unique: true });

// Admin audit and retention sweeps.
messageSchema.index({ schoolId: 1, createdAt: -1 });

// "What did this person send?" — safeguarding questions start here.
messageSchema.index({ schoolId: 1, "sender.id": 1, createdAt: -1 });

// ── Helpers ─────────────────────────────────────────────────────────────────

/**
 * The shape sent to clients.
 *
 * A deleted message keeps its place in the sequence — removing it would
 * leave a hole and make "5 unread" wrong — but surrenders its body and
 * attachments. Admins auditing get the real thing via a separate path.
 */
messageSchema.methods.toClientJSON = function () {
  const base = {
    _id:             this._id,
    conversationId:  this.conversationId,
    seq:             this.seq,
    sender:          this.sender,
    replyTo:         this.replyTo,
    systemEvent:     this.systemEvent,
    reactions:       this.reactions,
    deviceCreatedAt: this.deviceCreatedAt,
    createdAt:       this.createdAt,
    editedAt:        this.editedAt,
    isDeleted:       Boolean(this.deletedAt),
  };

  if (this.deletedAt) {
    return { ...base, body: null, attachments: [] };
  }

  // ── Attachments are signed HERE, at read time, not at upload time ──────
  // A stored attachment URL outlives any signature: it sits inside Message
  // documents for years and is re-served to every reader of the thread. The
  // stored value therefore stays unsigned and stable, and every client that
  // reads the message gets a fresh signature bound to that read — old
  // messages never break, and a link copied out of one dies with the week.
  //
  // The mobile caches these URLs in SQLite for the offline view, so a device
  // offline longer than the signature's life loses attachment previews until
  // it reconnects and the list is re-read. That is the accepted trade: an
  // expired preview is recoverable, a leaked permanent link is not.
  return {
    ...base,
    body: this.body,
    attachments: mediaSignature.signAttachmentUrls(this.attachments),
  };
};

module.exports =
  mongoose.models.Message || mongoose.model("Message", messageSchema);
