// backend/src/db/models/TermResult.js
"use strict";

const mongoose       = require("mongoose");
const { v4: uuidv4 } = require("uuid");

/**
 * TermResult — one per student per term per class.
 *
 * Stores the computed term average and per-sequence breakdown.
 * Generated by termGrading.service.js after exam results are processed.
 */

const sequenceAverageSchema = new mongoose.Schema(
  {
    sequence:     { type: Number, required: true },
    examId:       { type: String, default: null },
    average:      { type: Number, default: 0 },
    overallGrade: { type: String, default: null },
    isComplete:   { type: Boolean, default: false }, // both sequences in term have results
  },
  { _id: false }
);

const termResultSchema = new mongoose.Schema(
  {
    _id: { type: String, default: uuidv4 },

    schoolId:     { type: String, required: true, index: true },
    academicYear: { type: String, required: true, index: true },
    term:         { type: Number, required: true, min: 1, max: 3 },
    classId:      { type: String, required: true, index: true },
    studentId:    { type: String, required: true, index: true },

    // Denormalised
    studentName: { type: String, default: null },
    admissionNo: { type: String, default: null },
    className:   { type: String, default: null },

    // Per-sequence averages
    sequenceAverages: { type: [sequenceAverageSchema], default: [] },

    // Weighted term average (across sequences)
    termAverage:    { type: Number, default: 0 },
    overallGrade:   { type: String, default: null },
    overallRemark:  { type: String, default: null },

    // Rankings
    classPosition:  { type: Number, default: null },
    schoolPosition: { type: Number, default: null },
    totalInClass:   { type: Number, default: null },
    totalInSchool:  { type: Number, default: null },

    // Pass / fail
    isPassing: { type: Boolean, default: false },

    // Publishing
    isPublished: { type: Boolean, default: false },
    publishedAt: { type: Date,    default: null  },
    isLocked:    { type: Boolean, default: false },
    lockedAt:    { type: Date,    default: null  },

    // Sync
    syncStatus:   { type: String, enum: ["synced", "pending", "conflict"], default: "pending" },
    lastSyncedAt: { type: Date,   default: null },
    deletedAt:    { type: Date,   default: null },
  },
  {
    _id:       false,
    timestamps: true,
    toJSON:    { virtuals: true },
    toObject:  { virtuals: true },
  }
);

termResultSchema.index(
  { schoolId: 1, academicYear: 1, term: 1, classId: 1, studentId: 1 },
  { unique: true, sparse: true }
);
termResultSchema.index({ schoolId: 1, academicYear: 1, term: 1, classPosition: 1 });
termResultSchema.index({ schoolId: 1, isPublished: 1 });

module.exports = mongoose.model("TermResult", termResultSchema);
