// shared/adaptiveSupport/version.js
"use strict";

/**
 * The Adaptive Support Engine's version and vocabulary.
 *
 * At a review the engine reads the plan as it stood, the milestones that
 * occurred, the evidence that became available since the plan's evidence
 * boundary, the development change, any intervention outcome, what the
 * pupil reported and what the teacher observed — and answers with one
 * categorical outcome (CONTINUE, ADAPT, COMPLETE, PAUSE,
 * INSUFFICIENT_EVIDENCE), the reasons, and a bounded adaptation the human
 * may take or leave. "Failed" is not a word here. Nothing is optimised.
 */

const ADAPTIVE_SUPPORT_ENGINE_VERSION = "1.0.0";

const REVIEW_OUTCOMES = Object.freeze(["CONTINUE", "ADAPT", "COMPLETE", "PAUSE", "INSUFFICIENT_EVIDENCE"]);

const REASON_CODES = Object.freeze([
  "COMPLETION_CRITERIA_MET", "MILESTONES_REQUIRED_NOT_MET", "NEW_INDEPENDENT_EVIDENCE", "NO_NEW_INDEPENDENT_EVIDENCE", "EVIDENCE_IMPROVING", "EVIDENCE_STABLE",
  "EVIDENCE_DECLINING", "CONTRADICTORY_EVIDENCE", "CONTEXT_CHANGED", "CONSTRAINT_DOCUMENTED", "STUDENT_REPORTED_NOT_USEFUL", "STUDENT_REPORTED_TOO_DIFFICULT",
  "STUDENT_REPORTED_TOO_EASY", "STUDENT_REPORTED_NEED_SUPPORT", "STUDENT_REPORTED_RESOURCE_PROBLEM", "STUDENT_PREFERS_DIFFERENT_APPROACH", "STUDENT_REPORTED_USEFUL",
  "TEACHER_OBSERVED_PROGRESS", "TEACHER_OBSERVED_STABILITY", "TEACHER_OBSERVED_DIFFICULTY", "TEACHER_REPORTED_NO_NEW_EVIDENCE", "TEACHER_REPORTED_CONTEXT_CHANGED", "TEACHER_REQUESTED_SUPPORT",
  "INTERVENTION_OUTCOME_IMPROVED", "INTERVENTION_OUTCOME_DECLINED", "INTERVENTION_OUTCOME_MIXED", "INTERVENTION_OUTCOME_INSUFFICIENT", "MILESTONES_IN_PROGRESS", "MILESTONES_BLOCKED",
  "EXPECTED_CHANGE_NOT_SHOWN", "PLAN_STILL_GATHERING_EVIDENCE",
]);

/** Which adaptive action each situation suggests. Bounded; the human chooses. */
const ADAPTATIONS = Object.freeze({
  CONTRADICTORY_EVIDENCE: ["REPEAT_OBSERVATION", "DIFFERENT_PRACTICE"],
  EVIDENCE_DECLINING: ["TEACHER_SUPPORT", "DIFFERENT_PRACTICE"],
  STUDENT_REPORTED_NOT_USEFUL: ["DIFFERENT_PRACTICE", "NEW_CONTEXT"],
  STUDENT_PREFERS_DIFFERENT_APPROACH: ["DIFFERENT_PRACTICE", "NEW_CONTEXT"],
  STUDENT_REPORTED_TOO_DIFFICULT: ["LOWER_COMPLEXITY", "TEACHER_SUPPORT"],
  STUDENT_REPORTED_TOO_EASY: ["HIGHER_COMPLEXITY", "NEW_CONTEXT"],
  STUDENT_REPORTED_NEED_SUPPORT: ["TEACHER_SUPPORT", "PEER_SUPPORT"],
  STUDENT_REPORTED_RESOURCE_PROBLEM: ["RESOURCE_SUBSTITUTION"],
  CONSTRAINT_DOCUMENTED: ["RESOURCE_SUBSTITUTION", "WAIT_FOR_MORE_EVIDENCE"],
  TEACHER_OBSERVED_DIFFICULTY: ["TEACHER_SUPPORT", "LOWER_COMPLEXITY"],
  TEACHER_REQUESTED_SUPPORT: ["TEACHER_SUPPORT"],
  TEACHER_REPORTED_CONTEXT_CHANGED: ["NEW_CONTEXT"],
  CONTEXT_CHANGED: ["NEW_CONTEXT"],
  EXPECTED_CHANGE_NOT_SHOWN: ["DIFFERENT_PRACTICE", "REPEAT_OBSERVATION"],
  NO_NEW_INDEPENDENT_EVIDENCE: ["WAIT_FOR_MORE_EVIDENCE", "REPEAT_OBSERVATION"],
  MILESTONES_BLOCKED: ["RESOURCE_SUBSTITUTION", "TEACHER_SUPPORT"],
});

const RULES = Object.freeze({
  reviewsBeforeExpectedChangeIsJudged: 2,   // "the expected change is not shown" needs two reviews with new evidence and no change
});

const FORBIDDEN_KEYS = Object.freeze(["planScore", "goalScore", "riskScore", "successProbability", "completionProbability", "aptitudeScore", "readinessScore", "score", "probability", "ranking"]);

module.exports = { ADAPTIVE_SUPPORT_ENGINE_VERSION, REVIEW_OUTCOMES, REASON_CODES, ADAPTATIONS, RULES, FORBIDDEN_KEYS };
