// src/utils/idHelpers.js
"use strict";

/**
 * idHelpers.js
 *
 * Single source of truth for ID generation and validation across all
 * mobile services.
 *
 * Problem solved:
 *  - 4 different isGhostId() implementations across the codebase
 *  - 4 different generateUniqueId() functions with different formats
 *  - Sync logic breaking because local vs server IDs were indistinguishable
 *
 * Rules:
 *  - Server IDs are MongoDB ObjectIds (24-char hex) or UUIDs (36-char)
 *  - Local / offline IDs always start with "local_" prefix
 *  - Ghost IDs are anything else (corrupted, legacy, malformed)
 */

// ─── Regex constants ──────────────────────────────────────────────────────────

/**
 * MongoDB ObjectId: exactly 24 hexadecimal characters.
 * Example: "507f1f77bcf86cd799439011"
 */
const MONGODB_ID_REGEX = /^[a-f0-9]{24}$/i;

/**
 * UUID v4: standard 36-character hyphenated format.
 * Example: "550e8400-e29b-41d4-a716-446655440000"
 */
const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Every offline-created record must use this prefix.
 * Changing this string would break existing offline data.
 */
const LOCAL_PREFIX = "local_";

/**
 * Prefixes that indicate a corrupted / legacy / ghost ID.
 * These should never appear on real records.
 */
const GHOST_PREFIXES = ["server_", "legacy_", "sync_", "temp_"];

// ─── Validators ───────────────────────────────────────────────────────────────

/**
 * Returns true if the ID was generated by the server.
 * Accepts both MongoDB ObjectIds and UUIDs.
 *
 * @param {unknown} id
 * @returns {boolean}
 *
 * @example
 * isServerGeneratedId("507f1f77bcf86cd799439011") // true  (ObjectId)
 * isServerGeneratedId("550e8400-e29b-41d4-a716-446655440000") // true  (UUID)
 * isServerGeneratedId("local_lq1abc_xyz")          // false (local)
 * isServerGeneratedId(null)                         // false
 */
export const isServerGeneratedId = (id) => {
  if (!id) return false;
  const s = String(id).trim();
  return MONGODB_ID_REGEX.test(s) || UUID_REGEX.test(s);
};

/**
 * Returns true if the ID was generated offline by this app.
 * All offline IDs must start with LOCAL_PREFIX.
 *
 * @param {unknown} id
 * @returns {boolean}
 *
 * @example
 * isLocalId("local_lq1abc_xyz123") // true
 * isLocalId("507f1f77bcf86cd7")    // false (server)
 * isLocalId(null)                   // false
 */
export const isLocalId = (id) => {
  if (!id) return false;
  return String(id).startsWith(LOCAL_PREFIX);
};

/**
 * Returns true if the ID is corrupted / legacy / malformed.
 *
 * A ghost ID:
 *  - Is not a properly formatted server ID
 *  - Is not a properly formatted local ID
 *  - Optionally starts with a known ghost prefix
 *
 * @param {unknown} id
 * @returns {boolean}
 *
 * @example
 * isGhostId(null)               // true  — null is always ghost
 * isGhostId("")                 // true  — empty is always ghost
 * isGhostId("server_abc")       // true  — ghost prefix + short
 * isGhostId("local_lq1_xyz")    // false — valid local
 * isGhostId("507f1f77bcf86cd7") // false — valid server
 */
export const isGhostId = (id) => {
  if (!id) return true;
  const s = String(id).trim();
  if (!s) return true;

  // Valid server or local IDs are NOT ghosts
  if (isServerGeneratedId(s) || isLocalId(s)) return false;

  // Short string with a known ghost prefix = corrupted
  const hasGhostPrefix = GHOST_PREFIXES.some((p) => s.startsWith(p));
  if (hasGhostPrefix && s.length < 40) return true;

  return false;
};

/**
 * Returns true if an ID needs to be pushed to the server.
 *
 * @param {unknown} id
 * @returns {boolean}
 */
export const needsServerSync = (id) =>
  isLocalId(id) && !isServerGeneratedId(id);

// ─── Generators ───────────────────────────────────────────────────────────────

/**
 * Generates a new local ID for records created while offline.
 *
 * Format: "local_<base36-timestamp>_<random-8-chars>"
 * Example: "local_lq1abc12_x7k9mz3p"
 *
 * Properties:
 *  - Instantly recognizable as local (starts with "local_")
 *  - Sortable by creation time (base36 timestamp)
 *  - Collision-resistant (8 random chars)
 *
 * @returns {string}
 */
export const generateLocalId = () => {
  const ts   = Date.now().toString(36);
  const rand = Math.random().toString(36).substring(2, 10);
  return `${LOCAL_PREFIX}${ts}_${rand}`;
};

/**
 * Generates a UUID v4.
 * Uses crypto.randomUUID() when available (React Native >= 0.73 / Expo SDK 50+),
 * falls back to a pure-JS implementation.
 *
 * @returns {string} UUID v4 string
 */
export const generateUUID = () => {
  if (
    typeof crypto !== "undefined" &&
    typeof crypto.randomUUID === "function"
  ) {
    return crypto.randomUUID();
  }

  // Pure-JS fallback — not cryptographically secure but sufficient for IDs
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

// ─── Diagnostics ──────────────────────────────────────────────────────────────

/**
 * Returns a human-readable label for the origin of an ID.
 * Useful for debug logging.
 *
 * @param {unknown} id
 * @returns {"SERVER" | "LOCAL_OFFLINE" | "GHOST" | "UNKNOWN"}
 *
 * @example
 * getIdSource("507f1f77bcf86cd799439011") // "SERVER"
 * getIdSource("local_lq1abc_xyz")          // "LOCAL_OFFLINE"
 * getIdSource("server_abc")                // "GHOST"
 * getIdSource("some-random-string")        // "UNKNOWN"
 */
export const getIdSource = (id) => {
  if (isServerGeneratedId(id)) return "SERVER";
  if (isLocalId(id))           return "LOCAL_OFFLINE";
  if (isGhostId(id))           return "GHOST";
  return "UNKNOWN";
};